import { contextBridge, ipcRenderer } from "electron";
import type { HelmApi } from "../shared/types";

const api: HelmApi = {
    registerProject: (input) => ipcRenderer.invoke("projects:register", input),
    listProjects: () => ipcRenderer.invoke("projects:list"),
    updateProject: (id, patch) => ipcRenderer.invoke("projects:update", id, patch),
    deleteProject: (id) => ipcRenderer.invoke("projects:delete", id),
    detectProject: (repoPath) => ipcRenderer.invoke("projects:detect", repoPath),
    promote: (projectId) => ipcRenderer.invoke("projects:promote", projectId),
    createTask: (input) => ipcRenderer.invoke("tasks:create", input),
    listTasks: () => ipcRenderer.invoke("tasks:list"),
    setDependsOn: (taskId, ids) => ipcRenderer.invoke("tasks:setDependsOn", taskId, ids),
    startNow: (taskId) => ipcRenderer.invoke("tasks:startNow", taskId),
    getSchedulerState: () => ipcRenderer.invoke("scheduler:state"),
    setSchedulerPaused: (paused) => ipcRenderer.invoke("scheduler:setPaused", paused),
    dropIn: (taskId, fresh) => ipcRenderer.invoke("tasks:dropIn", taskId, fresh),
    resumeTask: (taskId) => ipcRenderer.invoke("tasks:resume", taskId),
    verifyAndMerge: (taskId) => ipcRenderer.invoke("tasks:verifyAndMerge", taskId),
    abandon: (taskId) => ipcRenderer.invoke("tasks:abandon", taskId),
    getVerifyState: (taskId) => ipcRenderer.invoke("tasks:verifyState", taskId),
    getProgress: (taskId) => ipcRenderer.invoke("tasks:progress", taskId),
    // M7 embedded terminal.
    ptyCreate: (opts) => ipcRenderer.invoke("pty:create", opts),
    ptyWrite: (id, data) => ipcRenderer.invoke("pty:write", id, data),
    ptyResize: (id, cols, rows) => ipcRenderer.invoke("pty:resize", id, cols, rows),
    ptyKill: (id) => ipcRenderer.invoke("pty:kill", id),
    ptyList: () => ipcRenderer.invoke("pty:list"),
    ptyAttach: (id) => ipcRenderer.invoke("pty:attach", id),
    ptyDetach: (id) => ipcRenderer.invoke("pty:detach", id),
    onPtyData: (cb) => { const h = (_e: unknown, id: string, chunk: string) => cb(id, chunk); ipcRenderer.on("pty:data", h); return () => { ipcRenderer.removeListener("pty:data", h); }; },
    onPtyExit: (cb) => { const h = (_e: unknown, id: string, code: number) => cb(id, code); ipcRenderer.on("pty:exit", h); return () => { ipcRenderer.removeListener("pty:exit", h); }; },
    onTasksChanged: (cb) => { ipcRenderer.on("tasks:changed", () => cb()); },
    onSnapshotChanged: (cb) => { ipcRenderer.on("snapshot:changed", (_e, taskId: string) => cb(taskId)); },
    // M16 conductor (absorbs M10's planner) + the M10 plan-rail push.
    openConductor: (projectId) => ipcRenderer.invoke("conductor:open", projectId),
    launchConductor: (projectId, fresh) => ipcRenderer.invoke("conductor:launch", projectId, fresh),
    onPlanChanged: (cb) => { ipcRenderer.on("plan:changed", (_e, projectId: string, state) => cb(projectId, state)); },
    preflightPlan: (projectId) => ipcRenderer.invoke("plans:preflight", projectId),
    cancelPreflight: (projectId) => ipcRenderer.invoke("plans:cancelPreflight", projectId),
    onPreflightProgress: (cb) => { const h = (_e: unknown, projectId: string, p: Parameters<typeof cb>[1]) => cb(projectId, p); ipcRenderer.on("preflight:progress", h); return () => { ipcRenderer.removeListener("preflight:progress", h); }; },
    listPlans: (projectId) => ipcRenderer.invoke("plans:list", projectId),
    getPlan: (planId) => ipcRenderer.invoke("plans:get", planId),
    approvePlan: (projectId, opts) => ipcRenderer.invoke("plans:approve", projectId, opts),
};
contextBridge.exposeInMainWorld("helm", api);
